import { z } from "zod";

/** Mirrors api PatientInput; constraints match backend pydantic exactly. */
export const patientSchema = z.object({
  age_years: z.coerce.number().min(18).max(110),
  sex: z.enum(["male", "female"]),
  bmi: z.coerce.number().min(12).max(70),
  lvef_pct: z.coerce.number().min(5).max(80),
  egfr: z.coerce.number().min(5).max(120),
  creatinine_mg_dl: z.coerce.number().min(0.3).max(15),
  hemoglobin_g_dl: z.coerce.number().min(4).max(20),
  albumin_g_dl: z.coerce.number().min(1.0).max(6.0),
  nt_probnp_pg_ml: z.coerce.number().min(0).max(70_000).optional().nullable(),
  // Aortic-valve hemodynamics (required for severity)
  aortic_valve_area_cm2: z.coerce.number().min(0.2).max(4.0),
  mean_aortic_gradient_mmhg: z.coerce.number().min(0).max(120),
  peak_aortic_velocity_m_per_s: z.coerce.number().min(1.0).max(7.0),
  // Concomitant valve / morphology
  aortic_regurgitation_grade: z.coerce.number().int().min(0).max(3).default(0),
  bicuspid_valve: z.boolean().default(false),
  // Comorbidities
  diabetes: z.boolean().default(false),
  chronic_lung_disease: z.boolean().default(false),
  prior_mi: z.boolean().default(false),
  prior_pci: z.boolean().default(false),
  prior_cabg: z.boolean().default(false),
  prior_stroke: z.boolean().default(false),
  peripheral_vascular_disease: z.boolean().default(false),
  atrial_fibrillation: z.boolean().default(false),
  prior_pacemaker: z.boolean().default(false),
  on_dialysis: z.boolean().default(false),
  nyha_class: z.enum(["I", "II", "III", "IV"]).default("II"),
  urgency: z.enum(["elective", "urgent", "emergent"]).default("elective"),
  gait_speed_m_per_s: z.coerce.number().min(0).max(2.5).optional().nullable(),
  five_chair_rises_s: z.coerce.number().min(3).max(120).optional().nullable(),
  clinical_frailty_scale: z.coerce.number().int().min(1).max(9).optional().nullable(),
  // CT-derived
  annular_area_mm2: z.coerce.number().min(200).max(900).optional().nullable(),
  annular_perimeter_mm: z.coerce.number().min(50).max(120).optional().nullable(),
  calcium_volume_au: z.coerce.number().min(0).max(8000).optional().nullable(),
  membranous_septum_length_mm: z.coerce.number().min(1).max(20).optional().nullable(),
  distance_to_left_main_mm: z.coerce.number().min(4).max(25).optional().nullable(),
  distance_to_right_coronary_mm: z.coerce.number().min(4).max(25).optional().nullable(),
  sinus_of_valsalva_diameter_mm: z.coerce.number().min(20).max(50).optional().nullable(),
});

export type PatientFormValues = z.infer<typeof patientSchema>;

// ------------------------------ Demo presets ------------------------------

export const demoPresets = {
  lowRisk: {
    label: "EHR pull · low-risk case",
    sublabel: "Mr. J.D. · 72M · PARTNER 3 profile · favorable anatomy",
    values: {
      age_years: 72,
      sex: "male" as const,
      bmi: 26.5,
      lvef_pct: 60,
      egfr: 70,
      creatinine_mg_dl: 1.0,
      hemoglobin_g_dl: 13.2,
      albumin_g_dl: 4.0,
      nt_probnp_pg_ml: 800,
      aortic_valve_area_cm2: 0.85,
      mean_aortic_gradient_mmhg: 42,
      peak_aortic_velocity_m_per_s: 4.1,
      aortic_regurgitation_grade: 1,
      bicuspid_valve: false,
      diabetes: false,
      chronic_lung_disease: false,
      prior_mi: false,
      prior_pci: false,
      prior_cabg: false,
      prior_stroke: false,
      peripheral_vascular_disease: false,
      atrial_fibrillation: false,
      prior_pacemaker: false,
      on_dialysis: false,
      nyha_class: "II" as const,
      urgency: "elective" as const,
      gait_speed_m_per_s: 1.0,
      five_chair_rises_s: null,
      clinical_frailty_scale: 3,
      annular_area_mm2: 460,
      annular_perimeter_mm: 76,
      calcium_volume_au: 420,
      membranous_septum_length_mm: 7.5,
      distance_to_left_main_mm: 13.5,
      distance_to_right_coronary_mm: 13.0,
      sinus_of_valsalva_diameter_mm: 33,
    },
  },
  intermediateRisk: {
    label: "EHR pull · intermediate-risk case",
    sublabel: "Ms. M.K. · 79F · SURTAVI profile · moderate calcium, MS borderline",
    values: {
      age_years: 79,
      sex: "female" as const,
      bmi: 28.0,
      lvef_pct: 50,
      egfr: 55,
      creatinine_mg_dl: 1.4,
      hemoglobin_g_dl: 11.5,
      albumin_g_dl: 3.6,
      nt_probnp_pg_ml: 2200,
      aortic_valve_area_cm2: 0.7,
      mean_aortic_gradient_mmhg: 48,
      peak_aortic_velocity_m_per_s: 4.4,
      aortic_regurgitation_grade: 1,
      bicuspid_valve: false,
      diabetes: true,
      chronic_lung_disease: false,
      prior_mi: true,
      prior_pci: true,
      prior_cabg: false,
      prior_stroke: false,
      peripheral_vascular_disease: false,
      atrial_fibrillation: true,
      prior_pacemaker: false,
      on_dialysis: false,
      nyha_class: "III" as const,
      urgency: "elective" as const,
      gait_speed_m_per_s: 0.7,
      five_chair_rises_s: null,
      clinical_frailty_scale: 5,
      annular_area_mm2: 510,
      annular_perimeter_mm: 81,
      calcium_volume_au: 1100,
      membranous_septum_length_mm: 4.8,
      distance_to_left_main_mm: 11.0,
      distance_to_right_coronary_mm: 12.0,
      sinus_of_valsalva_diameter_mm: 30,
    },
  },
  highRisk: {
    label: "EHR pull · high-risk case",
    sublabel: "Ms. R.P. · 84F · PARTNER 1A profile · challenging anatomy",
    values: {
      age_years: 84,
      sex: "female" as const,
      bmi: 24.0,
      lvef_pct: 42,
      egfr: 45,
      creatinine_mg_dl: 1.5,
      hemoglobin_g_dl: 10.8,
      albumin_g_dl: 3.5,
      nt_probnp_pg_ml: 4000,
      aortic_valve_area_cm2: 0.6,
      mean_aortic_gradient_mmhg: 55,
      peak_aortic_velocity_m_per_s: 4.7,
      aortic_regurgitation_grade: 2,
      bicuspid_valve: false,
      diabetes: true,
      chronic_lung_disease: true,
      prior_mi: true,
      prior_pci: true,
      prior_cabg: false,
      prior_stroke: false,
      peripheral_vascular_disease: true,
      atrial_fibrillation: true,
      prior_pacemaker: false,
      on_dialysis: false,
      nyha_class: "III" as const,
      urgency: "elective" as const,
      gait_speed_m_per_s: 0.6,
      five_chair_rises_s: null,
      clinical_frailty_scale: 6,
      annular_area_mm2: 470,
      annular_perimeter_mm: 77,
      calcium_volume_au: 1800,
      membranous_septum_length_mm: 4.2,
      distance_to_left_main_mm: 9.8,
      distance_to_right_coronary_mm: 11.0,
      sinus_of_valsalva_diameter_mm: 28,
    },
  },
} satisfies Record<string, { label: string; values: PatientFormValues; sublabel: string }>;
